
POST http://127.0.0.1:5000/api/notes
content-type: application/json

{
    "MRN":"c3f645b3e484211b2b864fb935c54c3d",
    "STAT":	1,
    "Age":	64,
    "Sex":	"M",
    "Triage": "64 M. Fall full flight of stairs. Maintaining airway, BP high, closed head injury s/p fall +ETOH",
    "max_limit":200
}
   
# {
#     "MRN":"c3f645b3e484211b2b864fb935c54c3d",
#     "STAT":	0,
#     "Age":	24,
#     "Sex":	"M",
#     "Triage": "Pt presents to the ED s/p fall from bike with headstrike, found to have SAH. Awake and alert.",
#     "max_limit":200
# }


###
GET http://127.0.0.1:5000/api/test/notes

###
GET http://127.0.0.1:5000/api/test/notes?start=0&end=10&max_limit=200

###
GET http://127.0.0.1:5000/api/demo
